./configure \
--disable-bsfs \
--disable-devices \
--disable-encoders \
--disable-muxers \
--enable-cross-compile \
--cross-prefix=arm-linux-androideabi- \
--arch=armv6j \
--cpu=arm1136j-s \
--target-os=linux \
--enable-pic \
--enable-librtmp
