./configure \
--disable-bsfs \
--disable-devices \
--disable-encoders \
--disable-muxers \
--enable-cross-compile \
--cross-prefix=arm-none-linux-gnueabi- \
--arch=armv7-a \
--cpu=cortex-a8 \
--target-os=linux \
--enable-pic
